[versions]
activity-compose = "1.10.1"
compose = "1.9.0"
core-ktx-version = "1.15.0"
lifecycle-runtime-ktx = "2.9.3"
logging-interceptor = "4.9.2"
material = "1.12.0"
nav-ktx = "2.9.3"
retrofit2 = "2.9.0"
datastore = "1.1.0"
hilt = "2.51.1"
constraintlayout = "2.2.1"
composeconstraint = "1.1.1"
composematerial = "1.3.2"
coil = "3.1.0"
composepaging = "3.3.6"





[libraries]
# Retrofit
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx-version" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "nav-ktx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "nav-ktx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
retrofit-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit2" }

# Compose
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material2 = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composematerial" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-animation = { module = "androidx.compose.animation:animation-graphics", version.ref = "compose" }
compose-constraint = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "composeconstraint" }
compose-paging = { group = "androidx.paging", name = "paging-compose", version.ref = "composepaging" }

# Compose Test
compose-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-tooling-ui = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }

# DataStore
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

# ConstraintLayout
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

# Coil 3
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

[bundles]
compose = ["compose-ui", "compose-material2", "compose-material3",
    "compose-tooling-preview", "androidx-compose-animation",
    "compose-constraint", "compose-paging"]
retrofit = ["retrofit2", "retrofit-converter"]
coil = ["coil-compose", "coil-network"]